// Code generated by mockery v2.42.2. DO NOT EDIT.

package repositories

import (
	context "context"
	entities "nutri-plans-api/entities"

	mock "github.com/stretchr/testify/mock"
)

// MockCountryRepository is an autogenerated mock type for the CountryRepository type
type MockCountryRepository struct {
	mock.Mock
}

// GetCountryByID provides a mock function with given fields: ctx, id
func (_m *MockCountryRepository) GetCountryByID(ctx context.Context, id uint) (*entities.Country, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCountryByID")
	}

	var r0 *entities.Country
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*entities.Country, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *entities.Country); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Country)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockCountryRepository creates a new instance of MockCountryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCountryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCountryRepository {
	mock := &MockCountryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
