// Code generated by mockery v2.42.2. DO NOT EDIT.

package token

import (
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockTokenUtil is an autogenerated mock type for the TokenUtil type
type MockTokenUtil struct {
	mock.Mock
}

// GenerateToken provides a mock function with given fields: uid, roleID
func (_m *MockTokenUtil) GenerateToken(uid uuid.UUID, roleID uint) (string, error) {
	ret := _m.Called(uid, roleID)

	if len(ret) == 0 {
		panic("no return value specified for GenerateToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, uint) (string, error)); ok {
		return rf(uid, roleID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, uint) string); ok {
		r0 = rf(uid, roleID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, uint) error); ok {
		r1 = rf(uid, roleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockTokenUtil creates a new instance of MockTokenUtil. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenUtil(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenUtil {
	mock := &MockTokenUtil{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
