name: Development CI/CD

on:
  pull_request:
    branches: [develop]

jobs:
  lint:
    name: Linting code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.0'
      - name: Golang lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

  build-test:
    name: Unit testing
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.0'
      - name: Run usecase coverage
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./usecases
      - name: Upload to codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Build image
        run: docker build -t nutri-plans-api-dev .
